# Generated by Django 3.1.5 on 2021-03-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('due_date', models.DateTimeField(max_length=40)),
                ('details', models.CharField(max_length=140)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
